Repository codesquad-member-2020/issue-tracker-03, pull requests merged in 2020-06, with the labels that each got.

#14 [#13] refactor: 디렉토리 구조 변경 및 재정의
  client/package-lock.json
  client/package.json
  client/src/components/Common/Footer.js
  client/src/components/Common/Header.js
  client/src/components/IssueList/Body/FilterSelector.js
  client/src/components/IssueList/Body/Item.js
  client/src/components/IssueList/Body/SelectCounter.js
  client/src/components/IssueList/Filters/Filter.js
  client/src/components/IssueList/Filters/index.js
  client/src/components/IssueList/Header/index.js
  client/src/components/IssueList/List/Article.js
  client/src/components/IssueList/List/index.js
  client/src/components/IssueList/Search/index.js
  client/src/containers/IssueList/BodyContainer.js
  client/src/containers/IssueList/HeaderContainer.js
  client/src/containers/IssueListContainer.js
  client/src/pages/IssueDetailPage.js
  client/src/pages/IssueListPage.js
  client/src/pages/LoginPage.js
Labels: fe

#22 Feature/be/issue 008: OAuth 기능
  BE/src/main/java/com/codesquad/issue/controller/LoginController.java
  BE/src/main/java/com/codesquad/issue/domain/account/Account.java
  BE/src/main/java/com/codesquad/issue/domain/account/AccountApiRequest.java
  BE/src/main/java/com/codesquad/issue/domain/account/AccountRepository.java
  BE/src/main/java/com/codesquad/issue/domain/account/AccountResponse.java
  BE/src/main/java/com/codesquad/issue/domain/account/AccountSaveDto.java
  BE/src/main/java/com/codesquad/issue/domain/github/GithubAccessToken.java
  BE/src/main/java/com/codesquad/issue/domain/github/GithubOAuth.java
  BE/src/main/java/com/codesquad/issue/global/config/WebConfig.java
  BE/src/main/java/com/codesquad/issue/global/error/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/utils/JwtUtils.java
  BE/src/main/java/com/codesquad/issue/service/AccountService.java
  BE/src/main/java/com/codesquad/issue/service/OAuthLoginService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/test/java/com/codesquad/issue/domain/account/AccountRepositoryTest.java
  BE/src/test/java/com/codesquad/issue/global/utils/JwtUtilsTest.java
  BE/src/test/java/com/codesquad/issue/service/UserServiceTest.java
  BE/src/test/resources/application.yml
Labels: be

#23 이슈 목록 화면, 체크박스 상태 구현
  client/.env.development
  client/src/api/issueList.js
  client/src/components/IssueList/List/Article.js
  client/src/components/IssueList/List/index.js
  client/src/containers/IssueListContainer.js
  client/src/index.js
  client/src/libs/asyncUtils.js
  client/src/modules/checkbox.js
  client/src/modules/index.js
  client/src/modules/issueList.js
  client/src/modules/issues.js
Labels: fe

#31 [FE] 체크박스 기능 수정
  client/src/components/IssueList/List/Article.js
  client/src/components/IssueList/List/index.js
  client/src/containers/IssueListContainer.js
  client/src/modules/checkbox.js
  client/src/modules/issueList.js
  client/yarn.lock
Labels: fe

#37 [FE] 로그인 관련 기능 추가
  client/.env.development
  client/.env.production
  client/config/webpack.config.js
  client/package.json
  client/src/App.js
  client/src/containers/FooterContainer.js
  client/src/containers/HeaderContainer.js
  client/src/modules/index.js
  client/src/modules/login.js
  client/src/pages/IssueListPage.js
  client/yarn.lock
Labels: fe

#41 목록 -> 상세화면 라우트 연동
  client/src/components/IssueList/List/Article.js
  client/src/components/IssueList/List/styled.js
Labels: fe

#43 [#42] modify: Alias 및 공통 레이아웃
  client/package-lock.json
  client/src/App.js
  client/src/components/IssueList/List/Article.js
  client/src/components/IssueList/List/index.js
  client/src/containers/IssueListContainer.js
Labels: fe

#45 이슈 목록 화면 스타일링 & 공통 레이아웃 스타일링 구현
  client/src/components/Common/GlobalTitles.js
  client/src/components/IssueList/List/Article.js
  client/src/components/IssueList/List/styled.js
  client/src/containers/FooterContainer.js
  client/src/containers/HeaderContainer.js
  client/src/index.js
  client/src/libs/fonts/GothicA1-Bold.ttf
  client/src/libs/fonts/GothicA1-Light.ttf
  client/src/libs/fonts/GothicA1-Medium.ttf
  client/src/libs/fonts/GothicA1-Regular.ttf
  client/src/libs/fonts/Montserrat-Bold.ttf
  client/src/libs/fonts/Montserrat-Light.ttf
  client/src/libs/fonts/Montserrat-Medium.ttf
  client/src/libs/fonts/Montserrat-Regular.ttf
  client/src/libs/fonts/Roboto-Bold.ttf
  client/src/libs/fonts/Roboto-Light.ttf
  client/src/libs/fonts/Roboto-Medium.ttf
  client/src/libs/fonts/Roboto-Regular.ttf
  client/src/libs/styles/GlobalStyle.js
Labels: fe

#48 [#47] 라우터 구조 수정
  client/src/App.js
  client/src/index.js
  client/src/routers/AppRouter.jsx
Labels: fe

#44 Feature/be/issue 009
  BE/build.gradle
  BE/src/main/java/com/codesquad/issue/controller/IssueRestController.java
  BE/src/main/java/com/codesquad/issue/controller/LabelController.java
  BE/src/main/java/com/codesquad/issue/controller/LoginController.java
  BE/src/main/java/com/codesquad/issue/domain/account/Account.java
  BE/src/main/java/com/codesquad/issue/domain/account/AccountRepository.java
  BE/src/main/java/com/codesquad/issue/domain/account/GithubAccount.java
  BE/src/main/java/com/codesquad/issue/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueRepository.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueResponse.java
  BE/src/main/java/com/codesquad/issue/domain/label/Label.java
  BE/src/main/java/com/codesquad/issue/domain/label/LabelRepository.java
  BE/src/main/java/com/codesquad/issue/global/config/GithubConfig.java
  BE/src/main/java/com/codesquad/issue/global/config/WebConfig.java
  BE/src/main/java/com/codesquad/issue/global/github/GithubAccessToken.java
  BE/src/main/java/com/codesquad/issue/global/github/GithubOAuth.java
  BE/src/main/java/com/codesquad/issue/service/AccountService.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/OAuthLoginService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
  BE/src/test/java/com/codesquad/issue/domain/account/AccountRepositoryTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
  BE/src/test/resources/application.yml
Labels: be

#49 [#47] 라우터 구조 수정
  client/src/App.js
  client/src/index.js
  client/src/routers/AppRouter.jsx
Labels: fe

#52 [FE] 로그인 기능 수정
  client/package.json
  client/src/App.js
  client/src/modules/login.js
  client/yarn.lock
Labels: fe

#56 [#55] fix: JSON 데이터 형태 변경으로 인한 이슈 목록 props 수정
  client/src/components/IssueList/List/Article.js
  client/src/components/IssueList/List/index.js
  client/src/components/IssueList/List/styled.js
  client/src/containers/IssueListContainer.js
Labels: fe

#59 [FE] 이슈 생성 페이지 구현
  client/.env.development
  client/.env.production
  client/package.json
  client/src/components/IssueCreate/CancelButton.js
  client/src/components/IssueCreate/ContentsEditor.js
  client/src/components/IssueCreate/SubmitButton.js
  client/src/components/IssueCreate/TitleInput.js
  client/src/components/IssueCreate/index.js
  client/src/containers/IssueCreateContainer.js
  client/src/index.js
  client/src/pages/IssueCreatePage.js
  client/yarn.lock
Labels: fe

#60 [FE] 라벨 리스트 페이지 구현
  client/.env.development
  client/.env.production
  client/src/api/labelList.js
  client/src/components/IssueCreate/CancelButton.js
  client/src/components/IssueCreate/SubmitButton.js
  client/src/components/LabelList/Counter/index.js
  client/src/components/LabelList/List/Article.js
  client/src/components/LabelList/List/index.js
  client/src/components/LabelList/Menu/index.js
  client/src/containers/LabelListContainer.js
  client/src/modules/index.js
  client/src/modules/labelList.js
  client/src/pages/LabelListPage.js
Labels: fe

#62 이슈 상세 페이지 스켈레톤 구현 (내부 데모)
  client/package-lock.json
  client/src/api/issueList.js
  client/src/components/IssueDetails/index.js
  client/src/containers/IssueDetailsContainer.js
  client/src/libs/asyncUtils.js
  client/src/modules/issueList.js
  client/src/pages/IssueDetailPage.js
Labels: fe

#66 아무렇게
  BE/.gitignore
  BE/appspec.yml
  BE/build.gradle
  BE/deploy.sh
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/issue/IssueApplication.java
  BE/src/main/java/com/codesquad/issue/controller/IssueRestController.java
  BE/src/main/java/com/codesquad/issue/controller/LabelController.java
  BE/src/main/java/com/codesquad/issue/controller/LoginController.java
  BE/src/main/java/com/codesquad/issue/domain/account/Account.java
  BE/src/main/java/com/codesquad/issue/domain/account/AccountRepository.java
  BE/src/main/java/com/codesquad/issue/domain/account/AccountResponse.java
  BE/src/main/java/com/codesquad/issue/domain/account/AccountSaveDto.java
  BE/src/main/java/com/codesquad/issue/domain/account/GithubAccount.java
  BE/src/main/java/com/codesquad/issue/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueRepository.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueResponse.java
  BE/src/main/java/com/codesquad/issue/domain/label/Label.java
  BE/src/main/java/com/codesquad/issue/domain/label/LabelRepository.java
  BE/src/main/java/com/codesquad/issue/global/config/GithubConfig.java
  BE/src/main/java/com/codesquad/issue/global/config/WebConfig.java
  BE/src/main/java/com/codesquad/issue/global/error/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/github/GithubAccessToken.java
  BE/src/main/java/com/codesquad/issue/global/github/GithubOAuth.java
  BE/src/main/java/com/codesquad/issue/global/utils/JwtUtils.java
  BE/src/main/java/com/codesquad/issue/service/AccountService.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/OAuthLoginService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
  BE/src/test/java/com/codesquad/issue/domain/account/AccountRepositoryTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
  BE/src/test/java/com/codesquad/issue/global/utils/JwtUtilsTest.java
  BE/src/test/java/com/codesquad/issue/service/UserServiceTest.java
  BE/src/test/resources/application.yml
Labels: be

#67 [#8] fix: 계정 찾을 때 계정이 있더라도 저장하는 것을 수정함.
  BE/src/main/java/com/codesquad/issue/service/AccountService.java
Labels: be

#68 Fix/be/issue 008 DB 경로 및 host 수정
  BE/src/main/resources/application.yml
Labels: be

#70 Fix/be/issue 008 yml JPA 설정 추가
  BE/src/main/java/com/codesquad/issue/controller/LoginController.java
  BE/src/main/resources/application.yml
Labels: be

#71 [#8] fix: yml github 설정 추가
  BE/src/main/resources/application.yml
Labels: be

#72 [#8] fix: yml github ID 설정 추가
  BE/src/main/resources/application.yml
Labels: be

#75 [FE] 공용 컴포넌트 구현
  client/src/components/Common/Button/NavigationButton.js
  client/src/components/Common/Button/SubmitButton.js
  client/src/components/Common/ButtonPanel.js
  client/src/components/IssueCreate/index.js
  client/src/containers/IssueCreateContainer.js
Labels: fe

#76 [FE] 상세 페이지 기능 구현
  client/src/api/issueCreate.js
  client/src/components/IssueCreate/index.js
  client/src/containers/IssueCreateContainer.js
Labels: fe

#77 [BE] issue-034
  BE/src/main/java/com/codesquad/issue/IssueApplication.java
  BE/src/main/java/com/codesquad/issue/controller/CommentController.java
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/controller/IssueRestController.java
  BE/src/main/java/com/codesquad/issue/controller/LabelController.java
  BE/src/main/java/com/codesquad/issue/controller/LoginController.java
  BE/src/main/java/com/codesquad/issue/domain/account/AccountRepository.java
  BE/src/main/java/com/codesquad/issue/domain/account/GithubAccount.java
  BE/src/main/java/com/codesquad/issue/domain/account/request/AccountSaveDto.java
  BE/src/main/java/com/codesquad/issue/domain/account/response/AccountResponse.java
  BE/src/main/java/com/codesquad/issue/domain/comment/Comment.java
  BE/src/main/java/com/codesquad/issue/domain/comment/CommentRepository.java
  BE/src/main/java/com/codesquad/issue/domain/comment/request/CommentModifyRequest.java
  BE/src/main/java/com/codesquad/issue/domain/comment/request/CommentSaveRequest.java
  BE/src/main/java/com/codesquad/issue/domain/comment/response/CommentResponse.java
  BE/src/main/java/com/codesquad/issue/domain/commmon/BaseTimeEntity.java
  BE/src/main/java/com/codesquad/issue/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueRepository.java
  BE/src/main/java/com/codesquad/issue/domain/issue/request/IssueCreateRequest.java
  BE/src/main/java/com/codesquad/issue/domain/issue/request/IssueModifyRequest.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueCreateResponse.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueDetailResponse.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueResponse.java
  BE/src/main/java/com/codesquad/issue/domain/label/LabelRepository.java
  BE/src/main/java/com/codesquad/issue/global/api/ApiError.java
  BE/src/main/java/com/codesquad/issue/global/api/ApiResult.java
  BE/src/main/java/com/codesquad/issue/global/error/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/CommentNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/IssueNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/github/GithubOAuth.java
  BE/src/main/java/com/codesquad/issue/global/utils/JwtUtils.java
  BE/src/main/java/com/codesquad/issue/service/AccountService.java
  BE/src/main/java/com/codesquad/issue/service/CommentService.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/OAuthLoginService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
  BE/src/test/java/com/codesquad/issue/IssueApplicationTests.java
  BE/src/test/java/com/codesquad/issue/domain/comment/CommentTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
  BE/src/test/java/com/codesquad/issue/global/utils/JwtUtilsTest.java
  BE/src/test/java/com/codesquad/issue/service/UserServiceTest.java
  BE/src/test/resources/application.yml
Labels: be

#84 [BE] dev 배포
  BE/src/main/java/com/codesquad/issue/IssueApplication.java
  BE/src/main/java/com/codesquad/issue/controller/CommentController.java
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/controller/IssueRestController.java
  BE/src/main/java/com/codesquad/issue/controller/LabelController.java
  BE/src/main/java/com/codesquad/issue/controller/LoginController.java
  BE/src/main/java/com/codesquad/issue/domain/account/AccountRepository.java
  BE/src/main/java/com/codesquad/issue/domain/account/GithubAccount.java
  BE/src/main/java/com/codesquad/issue/domain/account/request/AccountSaveDto.java
  BE/src/main/java/com/codesquad/issue/domain/account/response/AccountResponse.java
  BE/src/main/java/com/codesquad/issue/domain/comment/Comment.java
  BE/src/main/java/com/codesquad/issue/domain/comment/CommentRepository.java
  BE/src/main/java/com/codesquad/issue/domain/comment/request/CommentModifyRequest.java
  BE/src/main/java/com/codesquad/issue/domain/comment/request/CommentSaveRequest.java
  BE/src/main/java/com/codesquad/issue/domain/comment/response/CommentResponse.java
  BE/src/main/java/com/codesquad/issue/domain/commmon/BaseTimeEntity.java
  BE/src/main/java/com/codesquad/issue/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueRepository.java
  BE/src/main/java/com/codesquad/issue/domain/issue/request/IssueCreateRequest.java
  BE/src/main/java/com/codesquad/issue/domain/issue/request/IssueModifyRequest.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueCreateResponse.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueDetailResponse.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueResponse.java
  BE/src/main/java/com/codesquad/issue/domain/label/LabelRepository.java
  BE/src/main/java/com/codesquad/issue/global/api/ApiError.java
  BE/src/main/java/com/codesquad/issue/global/api/ApiResult.java
  BE/src/main/java/com/codesquad/issue/global/error/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/CommentNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/IssueNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/github/GithubOAuth.java
  BE/src/main/java/com/codesquad/issue/global/utils/JwtUtils.java
  BE/src/main/java/com/codesquad/issue/service/AccountService.java
  BE/src/main/java/com/codesquad/issue/service/CommentService.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/OAuthLoginService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
  BE/src/test/java/com/codesquad/issue/IssueApplicationTests.java
  BE/src/test/java/com/codesquad/issue/domain/comment/CommentTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
  BE/src/test/java/com/codesquad/issue/global/utils/JwtUtilsTest.java
  BE/src/test/java/com/codesquad/issue/service/UserServiceTest.java
  BE/src/test/resources/application.yml
Labels: be

#85 [FE] 헤더 수정, 이슈리스트 페이지 수정
  client/.env.development
  client/.env.production
  client/src/components/IssueList/Filters/index.js
  client/src/containers/HeaderContainer.js
  client/src/containers/IssueListContainer.js
  client/src/libs/styles/GlobalStyle.js
Labels: fe

#89 [#8] fix: AfterInstall 경로 수정
  BE/appspec.yml
Labels: be, bug

#97 [BE] issue-090 Milestone 기능
  BE/deploy.sh
  BE/src/main/java/com/codesquad/issue/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueMileStone.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueMilestoneRepository.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/Milestone.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/MilestoneRepository.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/request/MilestoneCreateRequest.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/request/MilestoneModifyRequest.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/response/MilestoneCreateResponse.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/response/MilestoneListResponse.java
  BE/src/main/java/com/codesquad/issue/global/error/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/MilestoneNotFoundException.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueMileStoneTest.java
  BE/src/test/java/com/codesquad/issue/domain/milestone/MilestoneRepositoryTest.java
  BE/src/test/resources/application.yml
Labels: be

#91 [BE] issue-081
  BE/build.gradle
  BE/src/main/java/com/codesquad/issue/controller/CommentController.java
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/controller/LabelController.java
  BE/src/main/java/com/codesquad/issue/domain/comment/request/CommentCreateRequest.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabel.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabelRepository.java
  BE/src/main/java/com/codesquad/issue/domain/label/Label.java
  BE/src/main/java/com/codesquad/issue/domain/label/request/LabelCreateRequest.java
  BE/src/main/java/com/codesquad/issue/domain/label/request/LabelModifyRequest.java
  BE/src/main/java/com/codesquad/issue/domain/label/response/LabelCreateResponse.java
  BE/src/main/java/com/codesquad/issue/domain/label/response/LabelResponse.java
  BE/src/main/java/com/codesquad/issue/global/api/ApiResult.java
  BE/src/main/java/com/codesquad/issue/global/error/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/LabelNotFoundException.java
  BE/src/main/java/com/codesquad/issue/service/CommentService.java
  BE/src/main/java/com/codesquad/issue/service/LabelService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
  BE/src/test/java/com/codesquad/issue/controller/LabelControllerTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueLabelTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
  BE/src/test/java/com/codesquad/issue/domain/label/LabelTest.java
Labels: be

#99 [BE] 라벨, 마일스톤 기능 구현
  BE/build.gradle
  BE/deploy.sh
  BE/src/main/java/com/codesquad/issue/controller/CommentController.java
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/controller/LabelController.java
  BE/src/main/java/com/codesquad/issue/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issue/domain/comment/request/CommentCreateRequest.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabel.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabelRepository.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueMileStone.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueMilestoneRepository.java
  BE/src/main/java/com/codesquad/issue/domain/label/Label.java
  BE/src/main/java/com/codesquad/issue/domain/label/request/LabelCreateRequest.java
  BE/src/main/java/com/codesquad/issue/domain/label/request/LabelModifyRequest.java
  BE/src/main/java/com/codesquad/issue/domain/label/response/LabelCreateResponse.java
  BE/src/main/java/com/codesquad/issue/domain/label/response/LabelResponse.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/Milestone.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/MilestoneRepository.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/request/MilestoneCreateRequest.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/request/MilestoneModifyRequest.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/response/MilestoneCreateResponse.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/response/MilestoneListResponse.java
  BE/src/main/java/com/codesquad/issue/global/api/ApiError.java
  BE/src/main/java/com/codesquad/issue/global/api/ApiResult.java
  BE/src/main/java/com/codesquad/issue/global/error/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/LabelNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/MilestoneNotFoundException.java
  BE/src/main/java/com/codesquad/issue/service/CommentService.java
  BE/src/main/java/com/codesquad/issue/service/LabelService.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
  BE/src/test/java/com/codesquad/issue/controller/LabelControllerTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueLabelTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueMileStoneTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
  BE/src/test/java/com/codesquad/issue/domain/label/LabelTest.java
  BE/src/test/java/com/codesquad/issue/domain/milestone/MilestoneRepositoryTest.java
  BE/src/test/resources/application.yml
Labels: be

#102 Feature/be/issue 090
  BE/src/main/java/com/codesquad/issue/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issue/global/error/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/CommentNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/IssueNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/MilestoneNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/issue/service/AccountService.java
  BE/src/main/java/com/codesquad/issue/service/CommentService.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
  BE/src/main/java/com/codesquad/issue/service/OAuthLoginService.java
  BE/src/test/java/com/codesquad/issue/domain/milestone/MilestoneRepositoryTest.java
Labels: be

#103 Dev be - issue 090
  BE/src/main/java/com/codesquad/issue/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issue/global/error/GlobalExceptionHandler.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/CommentNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/IssueNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/MilestoneNotFoundException.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/UserNotFoundException.java
  BE/src/main/java/com/codesquad/issue/service/AccountService.java
  BE/src/main/java/com/codesquad/issue/service/CommentService.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
  BE/src/main/java/com/codesquad/issue/service/OAuthLoginService.java
  BE/src/test/java/com/codesquad/issue/domain/milestone/MilestoneRepositoryTest.java
Labels: be

#104 [BE] Issue-098
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabel.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabelRepository.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueRepository.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueDetailResponse.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueResponse.java
  BE/src/main/java/com/codesquad/issue/global/error/exception/IssueNotFoundException.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/test/java/com/codesquad/issue/domain/comment/CommentTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueLabelTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueMileStoneTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
  BE/src/test/java/com/codesquad/issue/domain/milestone/MilestoneRepositoryTest.java
Labels: be

#114 [BE] issue-112 마일스톤 open/closed, 생성, 수정 시간
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issue/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/Milestone.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
Labels: be

#116 [#112] feat: milestone 데이터 추가
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
Labels: be

#113 [BE] issue-098 이슈-라벨 기능
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabel.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueLabelResponse.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/request/MilestoneModifyRequest.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
Labels: be

#117 [BE] CI / CD 브랜치 재설정
  .github/workflows/CD-BE.yml
  .github/workflows/CD-FE.yml
  .github/workflows/CI-BE.yml
  .github/workflows/CI-FE.yml
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issue/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabel.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueLabelResponse.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/Milestone.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/request/MilestoneModifyRequest.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
Labels: be

#119 API 형태 변경 적용, 상세페이지
  client/src/components/IssueDetails/IssueDetailesTitle.js
  client/src/components/IssueDetails/index.js
  client/src/components/IssueList/List/Article.js
  client/src/components/SidePanels/Panel.js
  client/src/components/SidePanels/index.js
  client/src/containers/IssueDetailsContainer.js
  client/src/modules/index.js
  client/src/modules/sidePanels.js
Labels: fe

#120 [#98] fix: 라벨 삭제 기능 수정
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabelRepository.java
  BE/src/main/java/com/codesquad/issue/service/LabelService.java
Labels: be

#122 [BE] 기능 구현, 수정
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issue/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabel.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueLabelRepository.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueLabelResponse.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/Milestone.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/request/MilestoneModifyRequest.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/LabelService.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
Labels: be

#121 Feature/be/new Issue Milestone 추가, 삭제, 변경
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueMileStone.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueMilestoneRepository.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueDetailResponse.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueResponse.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/response/MilestoneResponse.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueMileStoneTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
Labels: be

#123 [BE] 마일스톤 추가,삭제 기능
  BE/src/main/java/com/codesquad/issue/controller/IssueController.java
  BE/src/main/java/com/codesquad/issue/domain/issue/Issue.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueMileStone.java
  BE/src/main/java/com/codesquad/issue/domain/issue/IssueMilestoneRepository.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueDetailResponse.java
  BE/src/main/java/com/codesquad/issue/domain/issue/response/IssueResponse.java
  BE/src/main/java/com/codesquad/issue/domain/milestone/response/MilestoneResponse.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/resources/db/migration/V1.0.0__schema_init.sql
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueMileStoneTest.java
  BE/src/test/java/com/codesquad/issue/domain/issue/IssueTest.java
Labels: be

#131 [BE] mockdata 정리
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
Labels: be

#135 [FE] feat: 각 페이지 수정 및 구현
  client/.env.development
  client/.env.production
  client/package-lock.json
  client/package.json
  client/src/api/issueList.js
  client/src/api/labelList.js
  client/src/api/milestoneList.js
  client/src/components/IssueList/Filters/Counter.js
  client/src/components/IssueList/Filters/index.js
  client/src/components/LabelList/List/ArticleExpanded.js
  client/src/components/LabelList/List/ArticleNormal.js
  client/src/components/LabelList/List/index.js
  client/src/components/MilestoneList/List/Article.js
  client/src/components/MilestoneList/List/index.js
  client/src/components/SidePanels/Panel.js
  client/src/containers/IssueCreateContainer.js
  client/src/containers/IssueListContainer.js
  client/src/containers/LabelListContainer.js
  client/src/containers/MilestoneCreateContainer.js
  client/src/containers/MilestoneListContainer.js
  client/src/containers/MilestoneModifyContainer.js
  client/src/modules/index.js
  client/src/modules/milestoneList.js
  client/src/pages/IssueListPage.js
  client/src/pages/MilestoneCreatePage.js
  client/src/pages/MilestoneModifyPage.js
Labels: fe

#143 [#141] feat: milestone 상세화면 출력기능 추가
  BE/src/main/java/com/codesquad/issue/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
Labels: be

#144 Dev be 마일스톤 출력기능 추가
  BE/src/main/java/com/codesquad/issue/controller/MilestoneController.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
  BE/src/main/resources/db/migration/V1.0.1__add_mock_init.sql
Labels: be

#147 [#141] fix: milestone에 description 추가
  BE/src/main/java/com/codesquad/issue/domain/milestone/response/MilestoneResponse.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
Labels: be, bug

#148 Dev be
  BE/src/main/java/com/codesquad/issue/domain/milestone/response/MilestoneResponse.java
  BE/src/main/java/com/codesquad/issue/service/IssueService.java
  BE/src/main/java/com/codesquad/issue/service/MilestoneService.java
Labels: be
